pipeline {
    agent any
    stages{
        stage('SCM'){
            steps{
                git branch: 'master', url: 'https://github.com/SteffiJohnson/project1.git'
            }
        }
        stage('Build'){
            steps{
                sh '''
                cd app
                docker-compose up -d --build
            '''
            }
        }
    }
}
